[build]
  command = "bash ./netlify-build.sh"
  publish = "build/web"
  functions = "netlify/functions"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
